### ISSUE TITLE
UnsatisfiedLinkError when running jinfo on alpine 8 jdk

### ISSUE THREAD

**Issue by brianloss** [zulu-openjdk/zulu-openjdk#51] opened 2020-03-06 17:32 UTC
If I attempt to use `jinfo` or `jmap -heap` on the JDK 8 alpine image, I get an UnsatisfiedLinkError. For example, running:
```
docker run --cap-add=SYS_PTRACE --rm azul/zulu-openjdk-alpine:8 sh -c '$JAVA_HOME/bin/jinfo 1'
```
produces the following output:
```
Attaching to process ID 1, please wait...
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.tools.jinfo.JInfo.runTool(JInfo.java:108)
	at sun.tools.jinfo.JInfo.main(JInfo.java:76)
Caused by: java.lang.UnsatisfiedLinkError: sun.jvm.hotspot.debugger.linux.LinuxDebuggerLocal.init0()V
	at sun.jvm.hotspot.debugger.linux.LinuxDebuggerLocal.init0(Native Method)
	at sun.jvm.hotspot.debugger.linux.LinuxDebuggerLocal.<clinit>(LinuxDebuggerLocal.java:609)
	at sun.jvm.hotspot.HotSpotAgent.setupDebuggerLinux(HotSpotAgent.java:607)
	at sun.jvm.hotspot.HotSpotAgent.setupDebugger(HotSpotAgent.java:337)
	at sun.jvm.hotspot.HotSpotAgent.go(HotSpotAgent.java:304)
	at sun.jvm.hotspot.HotSpotAgent.attach(HotSpotAgent.java:140)
	at sun.jvm.hotspot.tools.Tool.start(Tool.java:185)
	at sun.jvm.hotspot.tools.Tool.execute(Tool.java:118)
	at sun.jvm.hotspot.tools.JInfo.main(JInfo.java:138)
	... 6 more
```

whereas running the debian-based image produces the expected output:
```
docker run --cap-add=SYS_PTRACE --rm azul/zulu-openjdk:8 sh -c '$JAVA_HOME/bin/jinfo 1'
Attaching to process ID 1, please wait...
Error attaching to process: Doesn't appear to be a HotSpot VM (could not find symbol "gHotSpotVMTypes" in remote process)
sun.jvm.hotspot.debugger.DebuggerException: Doesn't appear to be a HotSpot VM (could not find symbol "gHotSpotVMTypes" in remote process)
	at sun.jvm.hotspot.HotSpotAgent.setupVM(HotSpotAgent.java:412)
	at sun.jvm.hotspot.HotSpotAgent.go(HotSpotAgent.java:305)
	at sun.jvm.hotspot.HotSpotAgent.attach(HotSpotAgent.java:140)
	at sun.jvm.hotspot.tools.Tool.start(Tool.java:185)
	at sun.jvm.hotspot.tools.Tool.execute(Tool.java:118)
	at sun.jvm.hotspot.tools.JInfo.main(JInfo.java:138)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.tools.jinfo.JInfo.runTool(JInfo.java:108)
	at sun.tools.jinfo.JInfo.main(JInfo.java:76)
```
We expect this failure since PID 1 in the container isn't a docker process, but I get the same error in the alpine image if I actually create and run a Java program and then attempt to run jinfo on it.

Is there some other setup I need to do to get these commands to work in the alpine image?

**Comment by sgrinev** [comment] 2020-07-18 13:16
Sorry for the late answer, but I can't reproduce your case. If it's still relevant can you please adopt my example to demonstrate the problem:

```
/ # echo "public class S { public static void main(String... a) throws Exception {Thread.sleep(100000);}}" >  S.java
/ # java S.java &
/ # $JAVA_HOME/bin/jinfo $!
Java System Properties:
#Sat Jul 18 13:13:44 GMT 2020
awt.toolkit=sun.awt.X11.XToolkit
java.specification.version=11
sun.cpu.isalist=
sun.jnu.encoding=UTF-8
....
```

**Comment by qxo** [comment] 2020-07-21 01:50
> Sorry for the late answer, but I can't reproduce your case. If it's still relevant can you please adopt my example to demonstrate the problem:
> 
> ```
> / # echo "public class S { public static void main(String... a) throws Exception {Thread.sleep(100000);}}" >  S.java
> / # java S.java &
> / # $JAVA_HOME/bin/jinfo $!
> Java System Properties:
> #Sat Jul 18 13:13:44 GMT 2020
> awt.toolkit=sun.awt.X11.XToolkit
> java.specification.version=11
> sun.cpu.isalist=
> sun.jnu.encoding=UTF-8
> ....
> ```

It's a "azul/zulu-openjdk-alpine:8" issue, not java 11!
"java S.java " not work in java 8 !

Run your example in "azul/zulu-openjdk-alpine:8"  you will reproduce  the issue:
```
javac S.java && java S& $JAVA_HOME/bin/jinfo $!
```

**Comment by sgrinev** [comment] 2020-07-23 16:57
Hi, @qxo. Developers confirmed this to be alpine specific bug, to be addressed in the upcoming releases.

**Comment by sgrinev** [comment] 2020-11-16 16:11
fixed in october update

**Closed by sgrinev** 2020-11-16 16:11 UTC
