### ISSUE TITLE
Wrong image for azul/zulu-openjdk-alpine:11

### ISSUE THREAD

**Issue by maddenj-ie** [zulu-openjdk/zulu-openjdk#65] opened 2020-05-12 08:42 UTC
Using the same approach in #61, the following is observed when comparing the 11 and 11.0.7 versions:

`➜  ~ docker run -it azul/zulu-openjdk-alpine:11 apk list | grep zulu
zulu11-jre-11.0.7-r1 x86_64 {zulu11} (GPL-2.0-only WITH Classpath-exception-2.0) [installed]
zulu11-ca-jre-11.0.7-r1 x86_64 {zulu11-ca} (GPL-2.0-only WITH Classpath-exception-2.0) [installed]
zulu11-ca-jre-headless-11.0.7-r1 x86_64 {zulu11-ca} (GPL-2.0-only WITH Classpath-exception-2.0) [installed]
zulu11-jre-headless-11.0.7-r1 x86_64 {zulu11} (GPL-2.0-only WITH Classpath-exception-2.0) [installed]
`
`➜  ~ docker run -it azul/zulu-openjdk-alpine:11.0.7 apk list | grep zulu
zulu11-ca-jdk-11.0.7-r1 x86_64 {zulu11-ca} (GPL-2.0-only WITH Classpath-exception-2.0) [installed]
zulu11-jre-11.0.7-r1 x86_64 {zulu11} (GPL-2.0-only WITH Classpath-exception-2.0) [installed]
zulu11-ca-jdk-headless-11.0.7-r1 x86_64 {zulu11-ca} (GPL-2.0-only WITH Classpath-exception-2.0) [installed]
zulu11-jdk-headless-11.0.7-r1 x86_64 {zulu11} (GPL-2.0-only WITH Classpath-exception-2.0) [installed]
zulu11-jdk-11.0.7-r1 x86_64 {zulu11} (GPL-2.0-only WITH Classpath-exception-2.0) [installed]
zulu11-ca-jre-11.0.7-r1 x86_64 {zulu11-ca} (GPL-2.0-only WITH Classpath-exception-2.0) [installed]
zulu11-ca-jre-headless-11.0.7-r1 x86_64 {zulu11-ca} (GPL-2.0-only WITH Classpath-exception-2.0) [installed]
zulu11-jre-headless-11.0.7-r1 x86_64 {zulu11} (GPL-2.0-only WITH Classpath-exception-2.0) [installed]
`
The jdk does not appear to be present in 11. Thanks.

**Comment by sgrinev** [comment] 2020-05-12 14:43
Can you try, "docker pull azul/zulu-openjdk-alpine:11" please to update your local images? Because it works for me:

```
$ docker run -it azul/zulu-openjdk-alpine:11 apk list | grep zulu | grep jdk
zulu11-ca-jdk-11.0.7-r1 x86_64 {zulu11-ca} (GPL-2.0-only WITH Classpath-exception-2.0) [installed]
zulu11-ca-jdk-headless-11.0.7-r1 x86_64 {zulu11-ca} (GPL-2.0-only WITH Classpath-exception-2.0) [installed]
zulu11-jdk-headless-11.0.7-r1 x86_64 {zulu11} (GPL-2.0-only WITH Classpath-exception-2.0) [installed]
zulu11-jdk-11.0.7-r1 x86_64 {zulu11} (GPL-2.0-only WITH Classpath-exception-2.0) [installed]
```

**Comment by maddenj-ie** [comment] 2020-05-12 15:41
```
➜  ~ docker pull azul/zulu-openjdk-alpine:11
11: Pulling from azul/zulu-openjdk-alpine
cbdbe7a5bc2a: Already exists 
4fc96856165b: Pull complete 
Digest: sha256:1cc11a933fb817a6382bf571d2555402c28b8b2798d78e9785b27e8b9995557e
Status: Downloaded newer image for azul/zulu-openjdk-alpine:11
docker.io/azul/zulu-openjdk-alpine:11
➜  ~ docker run -it azul/zulu-openjdk-alpine:11 apk list | grep zulu | grep jdk
zulu11-ca-jdk-11.0.7-r1 x86_64 {zulu11-ca} (GPL-2.0-only WITH Classpath-exception-2.0) [installed]
zulu11-ca-jdk-headless-11.0.7-r1 x86_64 {zulu11-ca} (GPL-2.0-only WITH Classpath-exception-2.0) [installed]
zulu11-jdk-headless-11.0.7-r1 x86_64 {zulu11} (GPL-2.0-only WITH Classpath-exception-2.0) [installed]
zulu11-jdk-11.0.7-r1 x86_64 {zulu11} (GPL-2.0-only WITH Classpath-exception-2.0) [installed]
```
It works for me now, Thanks.

**Comment by henrist** [comment] 2020-05-12 15:41
I can confirm that the `azul/zulu-openjdk-alpine:11` tag did _not_ contain the JDK earlier today, as well as being wrong for the last 5 days. Checking again now it has been fixed. So I guess someone at your side did something before it "works for you".

It's a bit worrying that it seems you do not have control over what images have been pushed to the various tags on Docker Hub. Any reason this was not caught by #61 and #63? How can the tags be trusted going forward? I have a feeling this is not the last time we see this issue.

**Comment by sgrinev** [comment] 2020-05-12 15:49
Hi @henrist, I'm sorry for not being specific enough in my answer. 

It "works for me" because it's a duplicate of https://github.com/zulu-openjdk/zulu-openjdk/issues/61, which has been fixed a few days ago. There is no separate issue for the Zulu11; the same reasoning applies as in the https://github.com/zulu-openjdk/zulu-openjdk/issues/63#issuecomment-626110930. The problem has been addressed and covered by the current testing infrastructure.

**Closed by sgrinev** 2020-05-12 15:49 UTC

**Comment by henrist** [comment] 2020-05-12 15:55
Just to be clear: The issue was present today, _as well_. Pulling new image worked, because you did some changes _today_. Not "days ago".

I hope what you mean to say is that the underlying problem was fixed a few days ago, but you forgot/didn't update the tags until now, and that it will be correct going forward.

**Comment by sgrinev** [comment] 2020-05-12 15:56
that's weird, let me check

**Comment by sgrinev** [comment] 2020-05-12 16:47
Yes, @henrist, you are right. 

Everybody, I'm sorry for misinformation, zulu11 alpine image has been fixed only today. 

We'll elevate the release and testing processes to avoid errors in the future.

**Comment by henrist** [comment] 2020-05-12 18:20
Good to here you sorted it out. Thanks for the update.
